<?php
namespace App\Services;
use App\Models\Customer;use App\Models\LoyaltyRedemption;use App\Models\LoyaltyRule;use App\Models\LoyaltyTransaction;use App\Models\Order;use Illuminate\Support\Facades\DB;use Illuminate\Validation\ValidationException;
class LoyaltyService{
 public function award(Order $order):void{if(!$order->customer_id)return;foreach(LoyaltyRule::where('branch_id',$order->branch_id)->where('active',true)->get()as$rule){if($order->courtesy&&!$rule->courtesy_eligible)continue;$points=match($rule->type){'per_amount'=>floor((float)$order->total/(float)$rule->threshold)*(float)$rule->points,'per_order'=>(float)$rule->points,'product'=>$this->matching($order,'product_id',$rule)*(float)$rule->points,'category'=>$this->matching($order,'product_category_id',$rule)*(float)$rule->points};if($points>0)LoyaltyTransaction::firstOrCreate(['customer_id'=>$order->customer_id,'loyalty_rule_id'=>$rule->id,'order_id'=>$order->id,'type'=>'earned'],['points'=>$points,'remaining_points'=>$points,'expires_at'=>$rule->expires_days?now()->addDays($rule->expires_days):null]);}}
 private function matching(Order$o,string$field,LoyaltyRule$r):float{$ids=$r->conditions['ids']??[];return(float)$o->items()->whereHas('variant.product',fn($q)=>$q->whereIn($field,$ids))->sum('quantity');}
 public function redeem(Customer$c,float$points,$user,?Order$o=null,float$value=0):LoyaltyRedemption{return DB::transaction(function()use($c,$points,$user,$o,$value){$this->expire($c);if($c->points_balance<$points)throw ValidationException::withMessages(['points'=>'Saldo de puntos insuficiente.']);$left=$points;foreach($c->loyaltyTransactions()->where('remaining_points','>',0)->where(fn($q)=>$q->whereNull('expires_at')->orWhere('expires_at','>',now()))->orderByRaw('expires_at IS NULL')->orderBy('expires_at')->lockForUpdate()->get()as$x){$take=min($left,(float)$x->remaining_points);$x->decrement('remaining_points',$take);$left-=$take;if($left<=0)break;}$red=LoyaltyRedemption::create(['customer_id'=>$c->id,'order_id'=>$o?->id,'user_id'=>$user->id,'points'=>$points,'value'=>$value]);LoyaltyTransaction::create(['customer_id'=>$c->id,'order_id'=>$o?->id,'user_id'=>$user->id,'type'=>'redeemed','points'=>-$points,'remaining_points'=>0,'comment'=>'Canje #'.$red->id]);return$red;});}
 public function expire(?Customer$c=null):int{$q=LoyaltyTransaction::where('type','earned')->where('remaining_points','>',0)->where('expires_at','<=',now());if($c)$q->where('customer_id',$c->id);$n=0;foreach($q->get()as$x){$p=(float)$x->remaining_points;LoyaltyTransaction::create(['customer_id'=>$x->customer_id,'loyalty_rule_id'=>$x->loyalty_rule_id,'type'=>'expired','points'=>-$p,'remaining_points'=>0]);$x->update(['remaining_points'=>0]);$n++;}return$n;}
}
