<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;use App\Models\Customer;use App\Models\CustomerAddress;use App\Models\LoyaltyRule;use App\Models\Order;use App\Services\LoyaltyService;use Illuminate\Http\Request;
class CustomerController extends Controller{
 public function index(Request$r){return Customer::with('addresses')->where('branch_id',$r->user()->branch_id)->when($r->search,fn($q,$s)=>$q->where(fn($x)=>$x->where('name','like',"%$s%")->orWhere('phone','like',"%$s%")))->paginate(25);}public function store(Request$r){$d=$this->data($r);$d['branch_id']=$r->user()->branch_id;return response()->json(Customer::create($d),201);}public function show(Request$r,Customer$c,LoyaltyService$l){$this->own($r,$c);$l->expire($c);return$c->load(['addresses','orders.items','loyaltyTransactions'])->append('points_balance');}public function update(Request$r,Customer$c){$this->own($r,$c);$c->update($this->data($r,true));return$c;}
 public function address(Request$r,Customer$c){$this->own($r,$c);$d=$r->validate(['label'=>'required|string','address'=>'required|string','references'=>'nullable|string','map_url'=>'nullable|url','is_default'=>'sometimes|boolean']);if($d['is_default']??false)$c->addresses()->update(['is_default'=>false]);return response()->json($c->addresses()->create($d),201);}public function updateAddress(Request$r,Customer$c,CustomerAddress$a){$this->own($r,$c);abort_unless($a->customer_id===$c->id,404);$d=$r->validate(['label'=>'sometimes|string','address'=>'sometimes|string','references'=>'nullable|string','map_url'=>'nullable|url','is_default'=>'sometimes|boolean']);if($d['is_default']??false)$c->addresses()->whereKeyNot($a->id)->update(['is_default'=>false]);$a->update($d);return$a;}
 public function rules(Request$r){return LoyaltyRule::where('branch_id',$r->user()->branch_id)->get();}public function storeRule(Request$r){$d=$r->validate(['name'=>'required|string','type'=>'required|in:per_amount,per_order,product,category','threshold'=>'required|numeric|gt:0','points'=>'required|numeric|gt:0','expires_days'=>'nullable|integer|min:1','conditions'=>'nullable|array','courtesy_eligible'=>'sometimes|boolean','active'=>'sometimes|boolean']);$d['branch_id']=$r->user()->branch_id;return response()->json(LoyaltyRule::create($d),201);}public function redeem(Request$r,Customer$c,LoyaltyService$s){$this->own($r,$c);$d=$r->validate(['points'=>'required|numeric|gt:0','order_id'=>'nullable|exists:orders,id','value'=>'sometimes|numeric|min:0']);return response()->json($s->redeem($c,$d['points'],$r->user(),isset($d['order_id'])?Order::find($d['order_id']):null,$d['value']??0),201);}
 private function data(Request$r,bool$p=false):array{$x=$p?'sometimes|':'';return$r->validate(['name'=>$x.'required|string|max:150','phone'=>$x.'required|string|max:30','email'=>'nullable|email','birth_date'=>'nullable|date','notes'=>'nullable|string','active'=>'sometimes|boolean']);}private function own(Request$r,Customer$c):void{abort_unless($c->branch_id===$r->user()->branch_id,404);}
}
