<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;use App\Models\Combo;use App\Models\Modifier;use App\Models\Product;use App\Models\ProductCategory;use App\Models\ProductVariant;use App\Models\Recipe;use App\Services\RecipeResolver;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class ProductController extends Controller{
 public function index(Request $r){return Product::with(['category','variants.recipes.items.ingredient','flavors'])->where('branch_id',$r->user()->branch_id)->get();}
 public function categories(Request $r){return ProductCategory::where('branch_id',$r->user()->branch_id)->orderBy('sort_order')->get();}
 public function storeCategory(Request $r){$d=$r->validate(['name'=>'required|string|max:100','sort_order'=>'sometimes|integer|min:0']);$d['branch_id']=$r->user()->branch_id;return response()->json(ProductCategory::create($d),201);}
 public function store(Request $r){$d=$r->validate(['product_category_id'=>'nullable|exists:product_categories,id','name'=>'required|string|max:150','type'=>'required|in:pizza,wings,fries,nuggets,cone,beverage,extra,other','description'=>'nullable|string','variants'=>'required|array|min:1','variants.*.name'=>'required|string','variants.*.sku'=>'nullable|string','variants.*.price'=>'required|numeric|min:0','variants.*.max_flavors'=>'sometimes|integer|min:1','variants.*.allows_half_and_half'=>'sometimes|boolean','variants.*.allows_stuffed_crust'=>'sometimes|boolean','flavors'=>'nullable|array','flavors.*.name'=>'required|string','flavors.*.ingredient_id'=>'nullable|exists:ingredients,id']);$product=DB::transaction(function()use($r,$d){$p=Product::create(['branch_id'=>$r->user()->branch_id,'product_category_id'=>$d['product_category_id']??null,'name'=>$d['name'],'type'=>$d['type'],'description'=>$d['description']??null]);$p->variants()->createMany($d['variants']);$p->flavors()->createMany($d['flavors']??[]);return $p;});return response()->json($product->load(['variants','flavors']),201);}
 public function recipe(Request $r){$d=$r->validate(['product_variant_id'=>'required|exists:product_variants,id','product_flavor_id'=>'nullable|exists:product_flavors,id','name'=>'required|string','items'=>'required|array|min:1','items.*.ingredient_id'=>'required|exists:ingredients,id','items.*.quantity'=>'required|numeric|gt:0','items.*.component'=>'required|in:base,topping,sauce,packaging,other']);$recipe=DB::transaction(function()use($d){$x=Recipe::create(collect($d)->except('items')->all());$x->items()->createMany($d['items']);return $x;});return response()->json($recipe->load('items.ingredient'),201);}
 public function cloneRecipe(Request $r,Recipe $recipe){$d=$r->validate(['product_variant_id'=>'required|exists:product_variants,id','product_flavor_id'=>'nullable|exists:product_flavors,id','name'=>'required|string']);$clone=DB::transaction(function()use($recipe,$d){$x=Recipe::create($d);$x->items()->createMany($recipe->items->map->only(['ingredient_id','quantity','component'])->all());return $x;});return response()->json($clone->load('items'),201);}
 public function resolve(Request $r,ProductVariant $variant,RecipeResolver $resolver){$d=$r->validate(['flavor_ids'=>'array','flavor_ids.*'=>'integer|exists:product_flavors,id','modifier_ids'=>'array','modifier_ids.*'=>'integer|exists:modifiers,id']);return ['ingredients'=>$resolver->resolve($variant,$d['flavor_ids']??[],$d['modifier_ids']??[])];}
 public function modifiers(Request $r){return Modifier::with('items')->where('branch_id',$r->user()->branch_id)->get();}
 public function storeModifier(Request $r){$d=$r->validate(['name'=>'required|string','type'=>'required|in:add,remove,instruction,half_and_half,additional_flavor,stuffed_crust','price'=>'required|numeric|min:0','items'=>'array','items.*.ingredient_id'=>'required|exists:ingredients,id','items.*.quantity'=>'required|numeric']);$m=DB::transaction(function()use($r,$d){$m=Modifier::create(['branch_id'=>$r->user()->branch_id,'name'=>$d['name'],'type'=>$d['type'],'price'=>$d['price']]);$m->items()->createMany($d['items']??[]);return $m;});return response()->json($m->load('items'),201);}
 public function attachModifier(Request $r,ProductVariant $variant){$d=$r->validate(['modifier_id'=>'required|exists:modifiers,id','allowed'=>'sometimes|boolean','price_override'=>'nullable|numeric|min:0']);return response()->json($variant->modifierRules()->updateOrCreate(['modifier_id'=>$d['modifier_id']],$d),201);}
 public function combos(Request $r){return Combo::with(['items.variant.product','items.options'])->where('branch_id',$r->user()->branch_id)->get();}
 public function storeCombo(Request $r){$d=$r->validate(['name'=>'required|string','price'=>'required|numeric|min:0','items'=>'required|array|min:1','items.*.product_variant_id'=>'required|exists:product_variants,id','items.*.quantity'=>'required|numeric|gt:0','items.*.flavor_required'=>'sometimes|boolean','items.*.options'=>'array']);$combo=DB::transaction(function()use($r,$d){$c=Combo::create(['branch_id'=>$r->user()->branch_id,'name'=>$d['name'],'price'=>$d['price']]);foreach($d['items'] as $row){$item=$c->items()->create(collect($row)->except('options')->all());$item->options()->createMany($row['options']??[]);}return $c;});return response()->json($combo->load(['items.variant','items.options']),201);}
}
