<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;use App\Models\Ingredient;use App\Models\InventoryBatch;use App\Models\ProductionBatch;use App\Models\ProductionRecipe;use App\Services\InventoryService;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Validation\ValidationException;
class ProductionController extends Controller {
 public function recipes(Request $r){return ProductionRecipe::with(['items.ingredient.baseUnit','yieldUnit'])->where('branch_id',$r->user()->branch_id)->get();}
 public function storeRecipe(Request $r){$d=$r->validate(['name'=>'required|string|max:150','yield_quantity'=>'required|numeric|gt:0','yield_unit_id'=>'required|exists:units,id','shelf_life_days'=>'required|integer|min:0','items'=>'required|array|min:1','items.*.ingredient_id'=>'required|exists:ingredients,id','items.*.quantity'=>'required|numeric|gt:0']);$recipe=DB::transaction(function()use($r,$d){$recipe=ProductionRecipe::create(['branch_id'=>$r->user()->branch_id,'name'=>$d['name'],'yield_quantity'=>$d['yield_quantity'],'yield_unit_id'=>$d['yield_unit_id'],'shelf_life_days'=>$d['shelf_life_days']]);foreach($d['items'] as $item){$ingredient=Ingredient::findOrFail($item['ingredient_id']);abort_unless($ingredient->branch_id===$r->user()->branch_id,422);$recipe->items()->create($item);}return $recipe;});return response()->json($recipe->load(['items.ingredient','yieldUnit']),201);}
 public function updateRecipe(Request $r,ProductionRecipe $recipe){abort_unless($recipe->branch_id===$r->user()->branch_id,404);$d=$r->validate(['name'=>'required|string|max:150','yield_quantity'=>'required|numeric|gt:0','yield_unit_id'=>'required|exists:units,id','shelf_life_days'=>'required|integer|min:0','active'=>'sometimes|boolean','items'=>'required|array|min:1','items.*.ingredient_id'=>'required|exists:ingredients,id','items.*.quantity'=>'required|numeric|gt:0']);DB::transaction(function()use($recipe,$d){$recipe->update(collect($d)->except('items')->all());$recipe->items()->delete();$recipe->items()->createMany($d['items']);});return $recipe->load(['items.ingredient','yieldUnit']);}
 public function batches(Request $r){return ProductionBatch::with(['recipe','outputs.inventoryBatch'])->where('branch_id',$r->user()->branch_id)->latest('produced_at')->paginate(25);}
 public function produce(Request $r,InventoryService $inventory){$d=$r->validate(['production_recipe_id'=>'required|exists:production_recipes,id','output_ingredient_id'=>'required|exists:ingredients,id','multiplier'=>'required|numeric|gt:0','produced_at'=>'nullable|date','notes'=>'nullable|string','outputs'=>'nullable|array','outputs.*.portion_name'=>'required_with:outputs|string','outputs.*.quantity'=>'required_with:outputs|numeric|gt:0','outputs.*.grams_per_portion'=>'nullable|numeric|gt:0']);$recipe=ProductionRecipe::with('items.ingredient')->findOrFail($d['production_recipe_id']);$output=Ingredient::findOrFail($d['output_ingredient_id']);abort_unless($recipe->branch_id===$r->user()->branch_id&&$output->branch_id===$r->user()->branch_id,422);
  $batch=DB::transaction(function()use($r,$d,$recipe,$output,$inventory){$producedAt=isset($d['produced_at'])?now()->parse($d['produced_at']):now();$batch=ProductionBatch::create(['branch_id'=>$r->user()->branch_id,'production_recipe_id'=>$recipe->id,'user_id'=>$r->user()->id,'multiplier'=>$d['multiplier'],'produced_at'=>$producedAt,'expires_at'=>$producedAt->copy()->addDays($recipe->shelf_life_days)->toDateString(),'notes'=>$d['notes']??null]);foreach($recipe->items as $item){$needed=(float)$item->quantity*(float)$d['multiplier'];$result=$inventory->consumeFefo($item->ingredient,$needed,'production_input',$r->user(),$batch);if($result['shortage']>0)throw ValidationException::withMessages(['stock'=>"Faltan {$result['shortage']} {$item->ingredient->baseUnit->symbol} de {$item->ingredient->name}."]);}$quantity=(float)$recipe->yield_quantity*(float)$d['multiplier'];$lot=InventoryBatch::create(['branch_id'=>$batch->branch_id,'ingredient_id'=>$output->id,'lot_code'=>'PROD-'.$batch->id,'received_at'=>$producedAt->toDateString(),'expires_at'=>$batch->expires_at,'initial_quantity'=>$quantity,'available_quantity'=>0,'unit_cost'=>0]);$inventory->move($lot,$quantity,'production_output',$r->user(),$batch);$batch->outputs()->create(['ingredient_id'=>$output->id,'inventory_batch_id'=>$lot->id,'quantity'=>$quantity]);foreach($d['outputs']??[] as $portion)$batch->outputs()->create(['ingredient_id'=>$output->id,'inventory_batch_id'=>$lot->id,'quantity'=>$portion['quantity'],'portion_name'=>$portion['portion_name'],'grams_per_portion'=>$portion['grams_per_portion']??null]);return $batch;});return response()->json($batch->load(['recipe','outputs.inventoryBatch']),201);}
}
