<?php

use App\Http\Controllers\Api\AdministrationController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\CashDayController;
use App\Http\Controllers\Api\CatalogController;
use App\Http\Controllers\Api\ComboController;
use App\Http\Controllers\Api\CustomerController;
use App\Http\Controllers\Api\IngredientController;
use App\Http\Controllers\Api\InventoryController;
use App\Http\Controllers\Api\ModifierController;
use App\Http\Controllers\Api\OperationalSettingsController;
use App\Http\Controllers\Api\OrderController;
use App\Http\Controllers\Api\ProductController;
use App\Http\Controllers\Api\ProductionController;
use App\Http\Controllers\Api\PurchaseController;
use App\Http\Controllers\Api\RecipeController;
use App\Http\Controllers\Api\ReportController;
use App\Http\Controllers\Api\UserController;
use App\Http\Middleware\EnsureActiveUser;
use Illuminate\Support\Facades\Route;

Route::post('/login', [AuthController::class, 'login'])->middleware('throttle:10,1');
Route::get('/order-documents/{d}/download', [AdministrationController::class, 'download'])->middleware('signed')->name('order-documents.download');

Route::middleware(['auth:sanctum', EnsureActiveUser::class])->group(function (): void {
    Route::get('/me', [AuthController::class, 'me']);
    Route::post('/logout', [AuthController::class, 'logout']);
    Route::get('/preferences', [UserController::class, 'preferences']);
    Route::put('/preferences', [UserController::class, 'updatePreferences']);
    Route::get('/operational-settings', OperationalSettingsController::class)->middleware('permission:pos.use');
    Route::get('/catalogs/{catalog}', [CatalogController::class, 'index'])->middleware('permission:inventory.view');
    Route::post('/catalogs/{catalog}', [CatalogController::class, 'store'])->middleware('permission:admin.only');
    Route::put('/catalogs/{catalog}/{id}', [CatalogController::class, 'update'])->middleware('permission:admin.only');
    Route::delete('/catalogs/{catalog}/{id}', [CatalogController::class, 'destroy'])->middleware('permission:admin.only');
    Route::get('/ingredients', [IngredientController::class, 'index'])->middleware('permission:inventory.view');
    Route::get('/ingredients/{ingredient}', [IngredientController::class, 'show'])->middleware('permission:inventory.view');
    Route::post('/ingredients', [IngredientController::class, 'store'])->middleware('permission:admin.only');
    Route::match(['put', 'patch'], '/ingredients/{ingredient}', [IngredientController::class, 'update'])->middleware('permission:admin.only');
    Route::delete('/ingredients/{ingredient}', [IngredientController::class, 'destroy'])->middleware('permission:admin.only');
    Route::post('/ingredients/{ingredient}/presentations', [IngredientController::class, 'presentation'])->middleware('permission:admin.only');
    Route::put('/ingredients/{ingredient}/presentations/{presentation}', [IngredientController::class, 'updatePresentation'])->middleware('permission:admin.only');
    Route::delete('/ingredients/{ingredient}/presentations/{presentation}', [IngredientController::class, 'destroyPresentation'])->middleware('permission:admin.only');
    Route::get('/purchases', [PurchaseController::class, 'index'])->middleware('permission:purchases.manage');
    Route::post('/purchases', [PurchaseController::class, 'store'])->middleware('permission:purchases.manage');
    Route::get('/purchases/{purchase}', [PurchaseController::class, 'show'])->middleware('permission:purchases.manage');
    Route::get('/inventory/batches', [InventoryController::class, 'batches'])->middleware('permission:inventory.view');
    Route::get('/inventory/movements', [InventoryController::class, 'movements'])->middleware('permission:inventory.view');
    Route::get('/inventory/alerts', [InventoryController::class, 'alerts'])->middleware('permission:inventory.view');
    Route::post('/inventory/adjustments', [InventoryController::class, 'adjust'])->middleware('permission:admin.only');
    Route::get('/production-recipes', [ProductionController::class, 'recipes'])->middleware('permission:production.manage');
    Route::post('/production-recipes', [ProductionController::class, 'storeRecipe'])->middleware('permission:admin.only');
    Route::put('/production-recipes/{recipe}', [ProductionController::class, 'updateRecipe'])->middleware('permission:admin.only');
    Route::get('/production-batches', [ProductionController::class, 'batches'])->middleware('permission:production.manage');
    Route::post('/production-batches', [ProductionController::class, 'produce'])->middleware('permission:production.manage');
    Route::get('/product-categories', [ProductController::class, 'categories'])->middleware('permission:pos.use');
    Route::post('/product-categories', [ProductController::class, 'storeCategory'])->middleware('permission:admin.only');
    Route::get('/product-categories/{category}', [ProductController::class, 'showCategory'])->middleware('permission:pos.use');
    Route::match(['put', 'patch'], '/product-categories/{category}', [ProductController::class, 'updateCategory'])->middleware('permission:admin.only');
    Route::delete('/product-categories/{category}', [ProductController::class, 'destroyCategory'])->middleware('permission:admin.only');
    Route::get('/products', [ProductController::class, 'index'])->middleware('permission:pos.use');
    Route::post('/products', [ProductController::class, 'store'])->middleware('permission:admin.only');
    Route::get('/products/{product}', [ProductController::class, 'show'])->middleware('permission:pos.use');
    Route::match(['put', 'patch'], '/products/{product}', [ProductController::class, 'update'])->middleware('permission:admin.only');
    Route::delete('/products/{product}', [ProductController::class, 'destroy'])->middleware('permission:admin.only');
    Route::post('/products/{product}/variants', [ProductController::class, 'storeVariant'])->middleware('permission:admin.only');
    Route::match(['put', 'patch'], '/product-variants/{variant}', [ProductController::class, 'updateVariant'])->middleware('permission:admin.only');
    Route::delete('/product-variants/{variant}', [ProductController::class, 'destroyVariant'])->middleware('permission:admin.only');
    Route::post('/products/{product}/flavors', [ProductController::class, 'storeFlavor'])->middleware('permission:admin.only');
    Route::match(['put', 'patch'], '/product-flavors/{flavor}', [ProductController::class, 'updateFlavor'])->middleware('permission:admin.only');
    Route::delete('/product-flavors/{flavor}', [ProductController::class, 'destroyFlavor'])->middleware('permission:admin.only');
    Route::post('/recipes', [RecipeController::class, 'store'])->middleware('permission:admin.only');
    Route::get('/recipes/{recipe}', [RecipeController::class, 'show'])->middleware('permission:admin.only');
    Route::match(['put', 'patch'], '/recipes/{recipe}', [RecipeController::class, 'update'])->middleware('permission:admin.only');
    Route::delete('/recipes/{recipe}', [RecipeController::class, 'destroy'])->middleware('permission:admin.only');
    Route::post('/recipes/{recipe}/clone', [RecipeController::class, 'cloneRecipe'])->middleware('permission:admin.only');
    Route::post('/product-variants/{variant}/resolve', [RecipeController::class, 'resolve'])->middleware('permission:pos.use');
    Route::get('/modifiers', [ModifierController::class, 'index'])->middleware('permission:pos.use');
    Route::post('/modifiers', [ModifierController::class, 'store'])->middleware('permission:admin.only');
    Route::get('/modifiers/{modifier}', [ModifierController::class, 'show'])->middleware('permission:pos.use');
    Route::match(['put', 'patch'], '/modifiers/{modifier}', [ModifierController::class, 'update'])->middleware('permission:admin.only');
    Route::delete('/modifiers/{modifier}', [ModifierController::class, 'destroy'])->middleware('permission:admin.only');
    Route::post('/product-variants/{variant}/modifiers', [ModifierController::class, 'attach'])->middleware('permission:admin.only');
    Route::delete('/product-variants/{variant}/modifiers/{modifier}', [ModifierController::class, 'detach'])->middleware('permission:admin.only');
    Route::get('/combos', [ComboController::class, 'index'])->middleware('permission:pos.use');
    Route::post('/combos', [ComboController::class, 'store'])->middleware('permission:admin.only');
    Route::get('/combos/{combo}', [ComboController::class, 'show'])->middleware('permission:pos.use');
    Route::match(['put', 'patch'], '/combos/{combo}', [ComboController::class, 'update'])->middleware('permission:admin.only');
    Route::delete('/combos/{combo}', [ComboController::class, 'destroy'])->middleware('permission:admin.only');
    Route::get('/orders', [OrderController::class, 'index'])->middleware('permission:orders.view');
    Route::post('/orders', [OrderController::class, 'store'])->middleware('permission:pos.use');
    Route::get('/orders/{order}', [OrderController::class, 'show'])->middleware('permission:orders.view');
    Route::post('/orders/{order}/confirm', [OrderController::class, 'confirm'])->middleware('permission:pos.use');
    Route::post('/orders/{order}/send-to-kitchen', [OrderController::class, 'kitchen'])->middleware('permission:pos.use');
    Route::post('/orders/{order}/status', [OrderController::class, 'status'])->middleware('permission:pos.use,kitchen.use,delivery.use');
    Route::post('/orders/{order}/cancel', [OrderController::class, 'cancel'])->middleware('permission:pos.use');
    Route::get('/kitchen/orders', [OrderController::class, 'kitchenOrders'])->middleware('permission:kitchen.use');
    Route::get('/delivery/orders', [OrderController::class, 'deliveryOrders'])->middleware('permission:delivery.use');
    Route::post('/delivery/orders/{order}/payment-received', [OrderController::class, 'paymentReceived'])->middleware('permission:delivery.use');
    Route::get('/customers', [CustomerController::class, 'index'])->middleware('permission:customers.manage');
    Route::post('/customers', [CustomerController::class, 'store'])->middleware('permission:customers.manage');
    Route::get('/customers/{c}', [CustomerController::class, 'show'])->middleware('permission:customers.manage');
    Route::put('/customers/{c}', [CustomerController::class, 'update'])->middleware('permission:customers.manage');
    Route::post('/customers/{c}/addresses', [CustomerController::class, 'address'])->middleware('permission:customers.manage');
    Route::put('/customers/{c}/addresses/{a}', [CustomerController::class, 'updateAddress'])->middleware('permission:customers.manage');
    Route::delete('/customers/{c}/addresses/{a}', [CustomerController::class, 'destroyAddress'])->middleware('permission:customers.manage');
    Route::get('/customers/{c}/orders', [CustomerController::class, 'orders'])->middleware('permission:customers.manage');
    Route::get('/customers/{c}/loyalty', [CustomerController::class, 'loyalty'])->middleware('permission:customers.manage');
    Route::get('/loyalty-rules', [CustomerController::class, 'rules'])->middleware('permission:customers.manage');
    Route::post('/loyalty-rules', [CustomerController::class, 'storeRule'])->middleware('permission:admin.only');
    Route::put('/loyalty-rules/{rule}', [CustomerController::class, 'updateRule'])->middleware('permission:admin.only');
    Route::delete('/loyalty-rules/{rule}', [CustomerController::class, 'destroyRule'])->middleware('permission:admin.only');
    Route::post('/customers/{c}/redeem-points', [CustomerController::class, 'redeem'])->middleware('permission:customers.manage');
    Route::post('/customers/{c}/adjust-points', [CustomerController::class, 'adjustPoints'])->middleware('permission:admin.only');
    Route::get('/business-profile', [AdministrationController::class, 'profile'])->middleware('permission:admin.only');
    Route::put('/business-profile', [AdministrationController::class, 'updateProfile'])->middleware('permission:admin.only');
    Route::get('/settings', [AdministrationController::class, 'settings'])->middleware('permission:admin.only');
    Route::put('/settings', [AdministrationController::class, 'updateSettings'])->middleware('permission:admin.only');
    Route::post('/orders/{o}/generate-document', [AdministrationController::class, 'document'])->middleware('permission:documents.generate');
    Route::get('/cash-days', [CashDayController::class, 'index'])->middleware('permission:cash.manage');
    Route::get('/cash-days/current', [CashDayController::class, 'current'])->middleware('permission:cash.manage');
    Route::get('/cash-days/{day}', [CashDayController::class, 'show'])->middleware('permission:cash.manage');
    Route::post('/cash-days/open', [CashDayController::class, 'open'])->middleware('permission:cash.manage');
    Route::post('/cash-days/{day}/movements', [CashDayController::class, 'storeMovement'])->middleware('permission:cash.manage');
    Route::post('/cash-days/{day}/close', [CashDayController::class, 'close'])->middleware('permission:cash.manage');
    Route::get('/reports/cash-day', [AdministrationController::class, 'cashReport'])->middleware('permission:cash.manage');
    Route::post('/reports/daily', [AdministrationController::class, 'daily'])->middleware('permission:admin.only');
    Route::get('/reports/sales', [ReportController::class, 'sales'])->middleware('permission:admin.only');
    Route::get('/reports/products', [ReportController::class, 'products'])->middleware('permission:admin.only');
    Route::get('/reports/inventory', [ReportController::class, 'inventory'])->middleware('permission:admin.only');
    Route::get('/reports/purchases', [ReportController::class, 'purchases'])->middleware('permission:admin.only');
    Route::get('/reports/customers', [ReportController::class, 'customers'])->middleware('permission:admin.only');
    Route::get('/reports/profit', [ReportController::class, 'profit'])->middleware('permission:admin.only');
    Route::get('/reports/times', [ReportController::class, 'times'])->middleware('permission:admin.only');
    Route::get('/audit-logs', [AdministrationController::class, 'audits'])->middleware('permission:admin.only');
    Route::get('/users', [UserController::class, 'index'])->middleware('permission:admin.only');
    Route::post('/users', [UserController::class, 'store'])->middleware('permission:admin.only');
    Route::put('/users/{user}', [UserController::class, 'update'])->middleware('permission:admin.only');
    Route::delete('/users/{user}', [UserController::class, 'destroy'])->middleware('permission:admin.only');
    Route::put('/users/{user}/roles', [UserController::class, 'assignRole'])->middleware('permission:admin.only');
    Route::get('/roles', [UserController::class, 'roles'])->middleware('permission:admin.only');
    Route::put('/roles/{role}', [UserController::class, 'updateRole'])->middleware('permission:admin.only');
    Route::get('/permissions', [UserController::class, 'permissions'])->middleware('permission:admin.only');
    Route::post('/register-device', [UserController::class, 'device']);
    Route::get('/notifications', [UserController::class, 'notifications']);
    Route::post('/notifications/{id}/read', [UserController::class, 'read']);
});
