<?php
namespace Tests\Feature;
use App\Models\Ingredient;use App\Models\InventoryBatch;use App\Models\Product;use App\Models\ProductVariant;use App\Models\Recipe;use App\Models\Unit;use App\Models\User;use Illuminate\Foundation\Testing\RefreshDatabase;use Laravel\Sanctum\Sanctum;use Tests\TestCase;
class OrderFlowTest extends TestCase{use RefreshDatabase;private User $user;private Ingredient $ingredient;private ProductVariant $variant;
 protected function setUp():void{parent::setUp();$this->seed();$this->user=User::first();Sanctum::actingAs($this->user);$g=Unit::where('symbol','g')->first();$this->ingredient=Ingredient::create(['branch_id'=>$this->user->branch_id,'base_unit_id'=>$g->id,'name'=>'Queso']);$p=Product::create(['branch_id'=>$this->user->branch_id,'name'=>'Pizza','type'=>'pizza']);$this->variant=ProductVariant::create(['product_id'=>$p->id,'name'=>'Grande','price'=>200]);$r=Recipe::create(['product_variant_id'=>$this->variant->id,'name'=>'Pizza grande']);$r->items()->create(['ingredient_id'=>$this->ingredient->id,'quantity'=>250,'component'=>'base']);}
 private function stock(float $q):void{InventoryBatch::create(['branch_id'=>$this->user->branch_id,'ingredient_id'=>$this->ingredient->id,'received_at'=>today(),'initial_quantity'=>$q,'available_quantity'=>$q]);}
 private function order(string $status='confirmed'):array{return $this->postJson('/api/orders',['status'=>$status,'type'=>'pickup','items'=>[['product_variant_id'=>$this->variant->id,'quantity'=>1]],'payments'=>$status==='confirmed'?[['method'=>'cash','amount'=>200]]:[]])->assertCreated()->json();}
 public function test_inventory_is_only_deducted_when_sent_to_kitchen():void{$this->stock(500);$o=$this->order('pending_payment');$this->assertEquals(500,$this->ingredient->batches()->sum('available_quantity'));$this->assertDatabaseHas('stock_reservations',['order_id'=>$o['id'],'ingredient_id'=>$this->ingredient->id,'quantity'=>250]);$this->postJson("/api/orders/{$o['id']}/confirm",['payments'=>[['method'=>'cash','amount'=>200]]])->assertOk();$this->assertDatabaseMissing('stock_reservations',['order_id'=>$o['id']]);$this->assertEquals(500,$this->ingredient->batches()->sum('available_quantity'));$this->postJson("/api/orders/{$o['id']}/send-to-kitchen")->assertOk()->assertJsonPath('status','kitchen_pending');$this->assertEquals(250,$this->ingredient->batches()->sum('available_quantity'));}
 public function test_shortage_warns_but_does_not_block_kitchen():void{$this->stock(100);$o=$this->order();$this->postJson("/api/orders/{$o['id']}/send-to-kitchen")->assertOk()->assertJsonPath('status','kitchen_pending')->assertJsonPath('stock_warnings.0.shortage',150);$this->assertEquals(100,$this->ingredient->batches()->sum('available_quantity'));}
 public function test_cancel_before_preparation_returns_stock_but_after_start_records_waste():void{$this->stock(1000);$a=$this->order();$this->postJson("/api/orders/{$a['id']}/send-to-kitchen");$this->postJson("/api/orders/{$a['id']}/cancel")->assertOk();$this->assertEquals(1000,$this->ingredient->batches()->sum('available_quantity'));$b=$this->order();$this->postJson("/api/orders/{$b['id']}/send-to-kitchen");$this->postJson("/api/orders/{$b['id']}/status",['status'=>'preparing']);$this->postJson("/api/orders/{$b['id']}/cancel")->assertOk();$this->assertEquals(750,$this->ingredient->batches()->sum('available_quantity'));$this->assertDatabaseHas('inventory_adjustments',['reason'=>'preparation_error','quantity'=>250]);}
 public function test_daily_number_reuses_only_cancelled_tail():void{$this->stock(1000);$a=$this->order();$b=$this->order();$this->assertSame(2,$b['daily_number']);$this->postJson("/api/orders/{$b['id']}/cancel");$c=$this->order();$this->assertSame(2,$c['daily_number']);$this->postJson("/api/orders/{$a['id']}/cancel");$d=$this->order();$this->assertSame(3,$d['daily_number']);}
}
