<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration {public function up():void{
 Schema::create('product_categories',fn(Blueprint $t)=>[$t->id(),$t->foreignId('branch_id')->nullable()->constrained()->nullOnDelete(),$t->string('name'),$t->unsignedInteger('sort_order')->default(0),$t->boolean('active')->default(true),$t->timestamps()]);
 Schema::create('products',function(Blueprint $t){$t->id();$t->foreignId('branch_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('product_category_id')->nullable()->constrained()->nullOnDelete();$t->string('name');$t->enum('type',['pizza','wings','fries','nuggets','cone','beverage','extra','other']);$t->text('description')->nullable();$t->boolean('active')->default(true);$t->timestamps();});
 Schema::create('product_variants',function(Blueprint $t){$t->id();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('sku')->nullable()->unique();$t->decimal('price',12,2);$t->unsignedInteger('max_flavors')->default(1);$t->boolean('allows_half_and_half')->default(false);$t->boolean('allows_stuffed_crust')->default(false);$t->boolean('active')->default(true);$t->timestamps();});
 Schema::create('product_flavors',function(Blueprint $t){$t->id();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->string('name');$t->foreignId('ingredient_id')->nullable()->constrained()->nullOnDelete();$t->boolean('active')->default(true);$t->timestamps();});
 Schema::create('recipes',function(Blueprint $t){$t->id();$t->foreignId('product_variant_id')->constrained()->cascadeOnDelete();$t->foreignId('product_flavor_id')->nullable()->constrained()->cascadeOnDelete();$t->string('name');$t->boolean('active')->default(true);$t->timestamps();$t->unique(['product_variant_id','product_flavor_id'],'recipe_variant_flavor_unique');});
 Schema::create('recipe_items',function(Blueprint $t){$t->id();$t->foreignId('recipe_id')->constrained()->cascadeOnDelete();$t->foreignId('ingredient_id')->constrained();$t->decimal('quantity',16,4);$t->enum('component',['base','topping','sauce','packaging','other'])->default('other');$t->timestamps();$t->unique(['recipe_id','ingredient_id','component'],'recipe_item_component_unique');});
 Schema::create('modifiers',function(Blueprint $t){$t->id();$t->foreignId('branch_id')->nullable()->constrained()->nullOnDelete();$t->string('name');$t->enum('type',['add','remove','instruction','half_and_half','additional_flavor','stuffed_crust']);$t->decimal('price',12,2)->default(0);$t->boolean('active')->default(true);$t->timestamps();});
 Schema::create('modifier_recipe_items',function(Blueprint $t){$t->id();$t->foreignId('modifier_id')->constrained()->cascadeOnDelete();$t->foreignId('ingredient_id')->constrained();$t->decimal('quantity',16,4);$t->timestamps();});
 Schema::create('product_modifier_rules',function(Blueprint $t){$t->id();$t->foreignId('product_variant_id')->constrained()->cascadeOnDelete();$t->foreignId('modifier_id')->constrained()->cascadeOnDelete();$t->boolean('allowed')->default(true);$t->decimal('price_override',12,2)->nullable();$t->timestamps();$t->unique(['product_variant_id','modifier_id'],'variant_modifier_unique');});
 Schema::create('combos',function(Blueprint $t){$t->id();$t->foreignId('branch_id')->nullable()->constrained()->nullOnDelete();$t->string('name');$t->decimal('price',12,2);$t->boolean('active')->default(true);$t->timestamps();});
 Schema::create('combo_items',function(Blueprint $t){$t->id();$t->foreignId('combo_id')->constrained()->cascadeOnDelete();$t->foreignId('product_variant_id')->constrained();$t->decimal('quantity',10,2)->default(1);$t->boolean('flavor_required')->default(false);$t->timestamps();});
 Schema::create('combo_allowed_options',function(Blueprint $t){$t->id();$t->foreignId('combo_item_id')->constrained()->cascadeOnDelete();$t->foreignId('product_flavor_id')->nullable()->constrained()->cascadeOnDelete();$t->foreignId('modifier_id')->nullable()->constrained()->cascadeOnDelete();$t->timestamps();});
 }public function down():void{foreach(['combo_allowed_options','combo_items','combos','product_modifier_rules','modifier_recipe_items','modifiers','recipe_items','recipes','product_flavors','product_variants','products','product_categories'] as $x)Schema::dropIfExists($x);}};
