<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
 Schema::create('customers',function(Blueprint $t){$t->id();$t->foreignId('branch_id')->nullable()->constrained()->nullOnDelete();$t->string('name');$t->string('phone',30)->index();$t->string('email')->nullable();$t->date('birth_date')->nullable();$t->text('notes')->nullable();$t->boolean('active')->default(true);$t->timestamps();});
 Schema::create('customer_addresses',function(Blueprint $t){$t->id();$t->foreignId('customer_id')->constrained()->cascadeOnDelete();$t->string('label')->default('Principal');$t->text('address');$t->text('references')->nullable();$t->string('map_url')->nullable();$t->boolean('is_default')->default(false);$t->timestamps();});
 Schema::create('loyalty_rules',function(Blueprint $t){$t->id();$t->foreignId('branch_id')->nullable()->constrained()->nullOnDelete();$t->string('name');$t->enum('type',['per_amount','per_order','product','category']);$t->decimal('threshold',12,2)->default(1);$t->decimal('points',12,2);$t->unsignedInteger('expires_days')->nullable();$t->json('conditions')->nullable();$t->boolean('courtesy_eligible')->default(false);$t->boolean('active')->default(true);$t->timestamps();});
 Schema::create('loyalty_transactions',function(Blueprint $t){$t->id();$t->foreignId('customer_id')->constrained()->cascadeOnDelete();$t->foreignId('loyalty_rule_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('order_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->enum('type',['earned','redeemed','expired','adjustment']);$t->decimal('points',12,2);$t->decimal('remaining_points',12,2)->default(0);$t->dateTime('expires_at')->nullable();$t->text('comment')->nullable();$t->timestamps();});
 Schema::create('loyalty_redemptions',function(Blueprint $t){$t->id();$t->foreignId('customer_id')->constrained()->cascadeOnDelete();$t->foreignId('order_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('user_id')->constrained();$t->decimal('points',12,2);$t->decimal('value',12,2)->default(0);$t->timestamps();});
 Schema::table('orders',fn(Blueprint $t)=>$t->foreign('customer_id')->references('id')->on('customers')->nullOnDelete());
 }public function down():void{Schema::table('orders',fn(Blueprint $t)=>$t->dropForeign(['customer_id']));foreach(['loyalty_redemptions','loyalty_transactions','loyalty_rules','customer_addresses','customers']as$x)Schema::dropIfExists($x);}};
