<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
 Schema::create('business_profiles',function(Blueprint$t){$t->id();$t->foreignId('branch_id')->unique()->constrained()->cascadeOnDelete();$t->string('name');$t->string('phone',30)->nullable();$t->text('address')->nullable();$t->string('logo_path')->nullable();$t->string('primary_color',20)->default('#cf4b32');$t->string('tax_id')->nullable();$t->text('receipt_footer')->nullable();$t->timestamps();});
 Schema::create('settings',function(Blueprint$t){$t->id();$t->foreignId('branch_id')->nullable()->constrained()->cascadeOnDelete();$t->string('key');$t->json('value')->nullable();$t->string('type')->default('json');$t->timestamps();$t->unique(['branch_id','key']);});
 Schema::create('order_documents',function(Blueprint$t){$t->id();$t->foreignId('order_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained();$t->enum('type',['customer_html','customer_pdf','customer_image','kitchen','delivery']);$t->string('path')->nullable();$t->longText('content')->nullable();$t->timestamps();});
 Schema::create('cash_days',function(Blueprint$t){$t->id();$t->foreignId('branch_id')->constrained()->cascadeOnDelete();$t->date('date');$t->foreignId('opened_by')->constrained('users');$t->foreignId('closed_by')->nullable()->constrained('users')->nullOnDelete();$t->decimal('opening_amount',12,2)->default(0);$t->decimal('expected_amount',12,2)->default(0);$t->decimal('actual_amount',12,2)->nullable();$t->decimal('difference',12,2)->nullable();$t->dateTime('closed_at')->nullable();$t->timestamps();$t->unique(['branch_id','date']);});
 Schema::create('cash_movements',function(Blueprint$t){$t->id();$t->foreignId('cash_day_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained();$t->enum('type',['income','expense']);$t->decimal('amount',12,2);$t->string('category');$t->text('description')->nullable();$t->nullableMorphs('reference');$t->timestamps();});
 Schema::create('daily_reports',function(Blueprint$t){$t->id();$t->foreignId('branch_id')->constrained()->cascadeOnDelete();$t->date('date');$t->json('data');$t->string('path')->nullable();$t->timestamps();$t->unique(['branch_id','date']);});
 Schema::create('report_snapshots',function(Blueprint$t){$t->id();$t->foreignId('branch_id')->constrained()->cascadeOnDelete();$t->string('type');$t->dateTime('from');$t->dateTime('to');$t->json('filters')->nullable();$t->json('data');$t->timestamps();});
 Schema::create('audit_logs',function(Blueprint$t){$t->id();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('action');$t->string('auditable_type');$t->unsignedBigInteger('auditable_id')->nullable();$t->json('old_values')->nullable();$t->json('new_values')->nullable();$t->string('ip')->nullable();$t->text('comment')->nullable();$t->timestamps();$t->index(['auditable_type','auditable_id']);});
 }public function down():void{foreach(['audit_logs','report_snapshots','daily_reports','cash_movements','cash_days','order_documents','settings','business_profiles']as$x)Schema::dropIfExists($x);}};
